import json
import os


def save_project(project_json: str):

    project_json = project_json.replace("```json", "")
    project_json = project_json.replace("```", "")
    project_json = project_json.strip()

    os.makedirs("data", exist_ok=True)

    file_path = "data/projects.json"

    if not os.path.exists(file_path):
        with open(file_path, "w") as file:
            json.dump([], file)

    try:
        project = json.loads(project_json)

    except json.JSONDecodeError as e:
        print("\n❌ Invalid JSON generated by the model.")
        print(e)
        return

    with open(file_path, "r") as file:
        projects = json.load(file)

    projects.append(project)

    with open(file_path, "w") as file:
        json.dump(projects, file, indent=4)

    print("\n✅ Project saved successfully.")